### ISSUE TITLE
USER STORY: Landing/Home Page

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/forge-focus#1]
As a new user, I can instantly see information about the application, so that I can understand what the application is offering me.

### Acceptance Criteria

1. Favicon of app logo
2. App Logo and name stand out as the main title
3. Sites slogan, "Refine Your Aim, Forge Your Path: Setting Goals, Shaping Tasks." is clearly displayed
4. Clear information about the app provided
5. Images display are specific to whether the user is displaying the page on mobile or desktop
6. Bottom of the screen takes user to the sign up
7. Footer provides info about development of the app

### Tasks

- [ ] 1.  Add Favicon
- [ ] 2.  Create footer component
- [ ] 3.  Add footer content (shorten for mobile)
- [ ] 4.  Style footer
- [ ] 5.  Check and adjust general page styling
- [ ] 6.  Create home component
- [ ] 7.  Add landing page content
- [ ] 8.  Add and link up call to action buttons
- [ ] 9.  Style home
- [ ] 10.  Check responsivity
- [ ] 11.  Test on deployed site
