### ISSUE TITLE
USER STORY: NavBar Component

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/forge-focus#2]
As a user, a clear navigation bar is present throughout the application, this would help me easily navigate between different sections of the application.

### Acceptance Criteria

1. Ensure navigation bar is present at the top of all pages.
2. Links present to the user top aid in site navigation.
3. There is a site logo and when clicked will take the user back to the homepage/landing page
4. On smaller screens such as mobile devices, links are accessed by the means of a hamburger icon.
5. Navigation menu on smaller screens can be toggled on/off by means of clicking the hamburger icon or clicking just outside the menu.
6. Navigation menu is automatically toggled off when the page is changed.

### Tasks

- [ ] Add Navbar component file
- [ ] Import said component into App.js file
- [ ] Add the Navbar component from React Bootstrap
- [ ] Add content and edit component
- [ ] Create App.css file and adds any custom CSS
- [ ] Validate code using appropriate validators
- [ ] Create and run tests for code
- [ ] Test on the deployed site
